### ISSUE TITLE
PlantUML (puml) files are not displayed

### ISSUE THREAD

**Issue by kernoeb** [kernoeb/docker-docsify-pdf#2]
My command:

 ```
docker run --rm -it \
  --cap-add=SYS_ADMIN \
  --user $(id -u):$(id -g) \
  -v $(pwd)/docs:/home/node/docs:ro \
  -v $(pwd)/pdf:/home/node/pdf:rw \
  -v $(pwd)/pdf/my-cover.pdf:/home/node/resources/cover.pdf:ro \
  -e "PDF_OUTPUT_NAME=my-doc.pdf" \
  ghcr.io/kernoeb/docker-docsify-pdf:main
```

If I remove following line it's OK:
```markdown
[do_make_fdisp](./plantuml/do_make_fdisp.puml ':include :type=code plantuml')
```

_Originally posted by @EchoPouet in https://github.com/kernoeb/docker-docsify-pdf/issues/1#issuecomment-1225453477_

**Comment by kernoeb** [comment]
Okay, I just understood the issue

The non markdown / image files which are included are not sent in the context of the docker container (in the `.static` temporary directory)

I'll try something this afternoon, I have an idea

**Comment by kernoeb** [comment]
Nice !

<img width="682" alt="image" src="https://user-images.githubusercontent.com/24623168/186409273-0ea85422-ce69-4d57-b064-136eb1bcf97b.png">

Can you try the new main image ?

I added a `.puml` file example in the repo too

(https://github.com/imyelo/docsify-plantuml)

**Comment by EchoPouet** [comment]
I confirm. Thanks.

**Comment by johnholliday** [comment]
![image](https://user-images.githubusercontent.com/5294044/186633646-4dc3ff58-94b1-4c01-990e-7cfb22476cf4.png)

**Comment by johnholliday** [comment]
> Good
> 
> Did you pull the last version, and use the import like this ?
> 
> https://raw.githubusercontent.com/kernoeb/docker-docsify-pdf/main/docs/tutorials/documentation/test.md
> 
> (Can we continue the conversation on #2 ?)

The correct format when using the docsify-puml plugin is the double-bracketted !include, as in:
```
[[!include test.puml]]
```

**Comment by kernoeb** [comment]
I'm using docsify-plantuml (https://github.com/imyelo/docsify-plantuml), not docsify-puml (https://github.com/indieatom/docsify-puml) here

I used this issue `https://github.com/imyelo/docsify-plantuml/issues/23` to get the correct syntax

Docker docsify pdf try to find all included files (in common markdown syntax), and get the good relative location for the combined markdown created, so it can't magically support all cases

Maybe I can handle this other syntax : `[[!include my-chart.puml]]`, but I don't know if docsify-plantuml accept it, can you check ?

**Comment by johnholliday** [comment]
Unfortunately, docsify-plantuml doesn't work for external files using the new embed syntax.

### Produces a completely blank page (no content rendered on the page):
```
[SystemLandscape](_generated/puml/structurizr-1-SystemLandscape.puml ':include :type=code plantuml')
```

### Produces a blank image (everything else on the page is rendered properly):
````
```plantuml
[SystemLandscape](_generated/puml/structurizr-1-SystemLandscape.puml ':include :type=code plantuml')
```
````

### Produces a blank image when using **docsify-plantuml**, but renders correctly with **docsify-puml**:
````
```plantuml
[[!include _generated/puml/structurizr-1-SystemLandscape.puml]]
```
````

**Comment by kernoeb** [comment]
Okay thanks !

I just created a pull request and another branch (#3)
It seems to work for me using docsify-puml, with the first and the last syntax, but I'm not 100% sure it's okay, regexes are never perfect ahah

Check this commit : [`5f82a85` (#3)](https://github.com/kernoeb/docker-docsify-pdf/pull/3/commits/5f82a8513abd7dd076250e3a08e75fd8f9c12c02) 

You can try by pulling the `:puml` image instead of main

**Comment by johnholliday** [comment]
docker: error response from daemon: manifest unknown

**Comment by kernoeb** [comment]
Oops, sorry you're right, I disabled pushing to ghcr if it's a pull request

I merged in main branch, you can come back to main image

**Comment by johnholliday** [comment]
Still not working, but the error message is different.
Seems you are loading the "<!DOCTYPE html>" text that is throwing the parser off.

**Comment by kernoeb** [comment]
Is there any difference between this example and yours ?

https://raw.githubusercontent.com/kernoeb/docker-docsify-pdf/main/docs/tutorials/README.md

Maybe another include, spaces or I don't know
